# Generated by Django 4.1.3 on 2022-11-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='realtionship',
            new_name='relationship',
        ),
    ]
